version: 2.1
orbs:
  go: circleci/go@1.5.0
jobs:
  build:
    executor:
      name: go/default
      tag: '1.18'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          coverprofile: coverage.txt
          race: true
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  main:
    jobs:
      - build
