name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: "go test"
        run: go test -v .
